### ISSUE TITLE
the link has losed when make static

### ISSUE THREAD

**Issue by pupiles** [ncsa/ssh-auditor#5]
go get -t -v ./...
Fetching https://golang.org/x/crypto/ssh?go-get=1
https fetch failed: Get https://golang.org/x/crypto/ssh?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/crypto/ssh: unrecognized import path "golang.org/x/crypto/ssh" (https fetch: Get https://golang.org/x/crypto/ssh?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/crypto/ssh/terminal?go-get=1
https fetch failed: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
make: *** [static] Error 1

**Comment by JustinAzoff** [comment]
It looks like you are unable to connect to golang.org..  I think that is blocked in china and there is a special golang.google.cn setup instead.

I think if you run this it will fix it:

    git config --global url."https://golang.google.cn".insteadOf https://golang.org

or just add this to your ~/.gitconfig

    [url "https://golang.google.cn"]
	    insteadOf = https://golang.org

Alternatively I have binary releases if you just wan't to try it out and don't care about compiling it https://github.com/ncsa/ssh-auditor/releases
