### ISSUE TITLE
Ability to discover using list of ips instead of cidr ranges

### ISSUE THREAD

**Issue by im23pds** [ncsa/ssh-auditor#6]
Hello 
Consider adding a "-f" parameter so you can add a custom ip list

like：
./ssh-auditor discover -p 22 -f ip.txt

thanks

**Comment by JustinAzoff** [comment]
Good idea!

**Comment by im23pds** [comment]
@JustinAzoff 
thanks

**Comment by JustinAzoff** [comment]
I think this is easiest to do by moving the toplevel discover command to a new 'discover scan' command, and add a new 'discover fromfile' version.

**Comment by JustinAzoff** [comment]
I also did https://github.com/ncsa/ssh-auditor/commit/2cb844de06e5949d6dac5d5eb0ef36fe0463a5d1 which means you can discover a single address instead of requiring all entries be CIDR blocks
