### ISSUE TITLE
Blank password

### ISSUE THREAD

**Issue by sirmodok** [ncsa/ssh-auditor#7]
Is it possible to test for a username/blank password combination?

**Comment by JustinAzoff** [comment]
Yes, you just need to quote it when adding it via the CLI:
```

$ ssh-auditor cred list
$ ssh-auditor cred add root ''
INFO[10-22|16:57:59] added credential               user=root password= interval=14
$ ssh-auditor cred list
{"User":"root","Password":"","ScanInterval":14}
$
```

**Comment by sirmodok** [comment]
Thanks, I figured it out literally seconds after I posted that.

**Comment by JustinAzoff** [comment]
No problem, I figured in case anyone else has the same question it'll be answered :)

I also realized this case wasn't covered in the tests, so I added another test container and associated test case for it.
